// fleet-export.ts — generate HTML report from fleet state for sharing.
// produces a self-contained HTML file with fleet status, session details,
// task progress, cost breakdown, and health scores.

import type { DaemonSessionState, TaskState } from "./types.js";

export interface FleetReportData {
  generatedAt: string;
  version: string;
  sessions: DaemonSessionState[];
  tasks: TaskState[];
  fleetHealth: number;
  totalCostUsd: number;
  activeSessions: number;
  completedTasks: number;
}

/**
 * Generate a self-contained HTML report from fleet state.
 */
export function generateHtmlReport(data: FleetReportData): string {
  const sessionRows = data.sessions.map((s) => {
    const task = data.tasks.find((t) => t.sessionTitle === s.title);
    const goal = task ? (task.goal.length > 80 ? task.goal.slice(0, 77) + "..." : task.goal) : "—";
    const progress = task ? task.progress.length : 0;
    return `<tr>
      <td>${esc(s.title)}</td>
      <td><span class="status-${s.status}">${esc(s.status)}</span></td>
      <td>${esc(s.tool)}</td>
      <td>${esc(s.costStr ?? "—")}</td>
      <td>${progress}</td>
      <td>${esc(goal)}</td>
    </tr>`;
  }).join("\n");

  const taskRows = data.tasks.map((t) => {
    const goal = t.goal.length > 60 ? t.goal.slice(0, 57) + "..." : t.goal;
    const duration = t.createdAt && t.completedAt
      ? formatMs(t.completedAt - t.createdAt)
      : t.createdAt ? formatMs(Date.now() - t.createdAt) + " (running)" : "—";
    return `<tr>
      <td>${esc(t.sessionTitle)}</td>
      <td><span class="status-${t.status}">${esc(t.status)}</span></td>
      <td>${esc(goal)}</td>
      <td>${t.progress.length}</td>
      <td>${duration}</td>
    </tr>`;
  }).join("\n");

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>aoaoe Fleet Report — ${data.generatedAt}</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: system-ui, -apple-system, sans-serif; background: #0d1117; color: #c9d1d9; padding: 2rem; }
  h1, h2 { color: #58a6ff; margin-bottom: 1rem; }
  .summary { display: flex; gap: 2rem; margin-bottom: 2rem; flex-wrap: wrap; }
  .card { background: #161b22; border: 1px solid #30363d; border-radius: 8px; padding: 1.5rem; min-width: 150px; }
  .card .value { font-size: 2rem; font-weight: bold; color: #58a6ff; }
  .card .label { color: #8b949e; font-size: 0.85rem; }
  table { width: 100%; border-collapse: collapse; margin-bottom: 2rem; }
  th, td { padding: 0.5rem 1rem; text-align: left; border-bottom: 1px solid #30363d; }
  th { color: #8b949e; font-weight: 600; }
  .status-working, .status-running { color: #3fb950; }
  .status-active { color: #3fb950; }
  .status-completed { color: #58a6ff; }
  .status-error, .status-failed { color: #f85149; }
  .status-idle, .status-paused, .status-pending { color: #d29922; }
  footer { color: #484f58; font-size: 0.8rem; margin-top: 2rem; }
</style>
</head>
<body>
<h1>aoaoe Fleet Report</h1>
<p style="color:#8b949e">Generated: ${esc(data.generatedAt)} &bull; Version: ${esc(data.version)}</p>

<div class="summary">
  <div class="card"><div class="value">${data.sessions.length}</div><div class="label">Sessions</div></div>
  <div class="card"><div class="value">${data.activeSessions}</div><div class="label">Active</div></div>
  <div class="card"><div class="value">${data.fleetHealth}/100</div><div class="label">Fleet Health</div></div>
  <div class="card"><div class="value">$${data.totalCostUsd.toFixed(2)}</div><div class="label">Total Cost</div></div>
  <div class="card"><div class="value">${data.completedTasks}</div><div class="label">Completed Tasks</div></div>
</div>

<h2>Sessions</h2>
<table>
  <thead><tr><th>Title</th><th>Status</th><th>Tool</th><th>Cost</th><th>Progress</th><th>Goal</th></tr></thead>
  <tbody>${sessionRows}</tbody>
</table>

<h2>Tasks</h2>
<table>
  <thead><tr><th>Session</th><th>Status</th><th>Goal</th><th>Progress</th><th>Duration</th></tr></thead>
  <tbody>${taskRows}</tbody>
</table>

<footer>Generated by aoaoe v${esc(data.version)} — <a href="https://github.com/Talador12/agent-of-agent-of-empires" style="color:#58a6ff">GitHub</a></footer>
</body>
</html>`;
}

/**
 * Build report data from current fleet state.
 */
export function buildReportData(
  sessions: readonly DaemonSessionState[],
  tasks: readonly TaskState[],
  version: string,
): FleetReportData {
  let totalCost = 0;
  for (const s of sessions) {
    if (s.costStr) {
      const match = s.costStr.match(/\$(\d+(?:\.\d+)?)/);
      if (match) totalCost += parseFloat(match[1]);
    }
  }

  const scores = sessions.map((s) => s.status === "working" || s.status === "running" ? 80 : s.status === "error" ? 20 : 50);
  const fleetHealth = scores.length > 0 ? Math.round(scores.reduce((a, b) => a + b, 0) / scores.length) : 100;

  return {
    generatedAt: new Date().toISOString(),
    version,
    sessions: [...sessions],
    tasks: [...tasks],
    fleetHealth,
    totalCostUsd: totalCost,
    activeSessions: sessions.filter((s) => s.status === "working" || s.status === "running").length,
    completedTasks: tasks.filter((t) => t.status === "completed").length,
  };
}

function esc(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

function formatMs(ms: number): string {
  if (ms < 60_000) return `${Math.round(ms / 1000)}s`;
  if (ms < 3_600_000) return `${Math.round(ms / 60_000)}m`;
  const h = Math.floor(ms / 3_600_000);
  const m = Math.round((ms % 3_600_000) / 60_000);
  return m > 0 ? `${h}h ${m}m` : `${h}h`;
}
