import { describe, it } from "node:test";
import * as assert from "node:assert/strict";
import { buildTranscript, transcriptStats, formatTranscriptPreview } from "./session-transcript-export.js";
import type { TranscriptInput } from "./session-transcript-export.js";

function makeInput(overrides: Partial<TranscriptInput> = {}): TranscriptInput {
  return {
    sessionTitle: "alpha", goal: "Build auth system", repo: "github/app",
    status: "active", startedAt: Date.now() - 3_600_000, costUsd: 5.50,
    progressEntries: [{ at: Date.now() - 1800_000, summary: "Started auth module" }],
    recentOutput: ["line 1", "line 2", "All tests passed"],
    actions: [{ at: Date.now() - 900_000, action: "send_input", detail: "nudge" }],
    ...overrides,
  };
}

describe("buildTranscript", () => {
  it("produces valid markdown with header", () => {
    const md = buildTranscript(makeInput());
    assert.ok(md.startsWith("# Session Transcript: alpha"));
  });

  it("includes metadata table", () => {
    const md = buildTranscript(makeInput());
    assert.ok(md.includes("| Goal |"));
    assert.ok(md.includes("Build auth system"));
  });

  it("includes progress section", () => {
    const md = buildTranscript(makeInput());
    assert.ok(md.includes("## Progress"));
    assert.ok(md.includes("Started auth module"));
  });

  it("includes actions section", () => {
    const md = buildTranscript(makeInput());
    assert.ok(md.includes("## Actions"));
    assert.ok(md.includes("send_input"));
  });

  it("includes recent output in code block", () => {
    const md = buildTranscript(makeInput());
    assert.ok(md.includes("## Recent Output"));
    assert.ok(md.includes("```"));
    assert.ok(md.includes("All tests passed"));
  });

  it("strips ANSI codes from output", () => {
    const md = buildTranscript(makeInput({ recentOutput: ["\x1b[31mred text\x1b[0m"] }));
    assert.ok(md.includes("red text"));
    assert.ok(!md.includes("\x1b"));
  });

  it("skips empty sections", () => {
    const md = buildTranscript(makeInput({ progressEntries: [], actions: [] }));
    assert.ok(!md.includes("## Progress"));
    assert.ok(!md.includes("## Actions"));
  });

  it("includes generation footer", () => {
    const md = buildTranscript(makeInput());
    assert.ok(md.includes("Generated by aoaoe"));
  });
});

describe("transcriptStats", () => {
  it("counts lines and sections", () => {
    const md = buildTranscript(makeInput());
    const stats = transcriptStats(md);
    assert.ok(stats.lines > 10);
    assert.ok(stats.sections >= 2);
    assert.ok(stats.chars > 100);
  });
});

describe("formatTranscriptPreview", () => {
  it("shows preview with stats", () => {
    const lines = formatTranscriptPreview(makeInput());
    assert.ok(lines[0].includes("Transcript"));
    assert.ok(lines[0].includes("alpha"));
    assert.ok(lines.some((l) => l.includes("more lines")));
  });
});
