// session-transcript-export.ts — export full session transcript as markdown.
// captures session metadata, goal, progress entries, output snippets, and
// timeline into a self-contained markdown document for archival or sharing.

export interface TranscriptEntry {
  timestamp: number;
  type: "progress" | "output" | "action" | "event";
  content: string;
}

export interface TranscriptInput {
  sessionTitle: string;
  goal: string;
  repo: string;
  status: string;
  startedAt: number;
  costUsd: number;
  progressEntries: Array<{ at: number; summary: string }>;
  recentOutput: string[];
  actions: Array<{ at: number; action: string; detail: string }>;
}

/**
 * Build a markdown transcript from session data.
 */
export function buildTranscript(input: TranscriptInput): string {
  const lines: string[] = [];
  const started = new Date(input.startedAt).toISOString().slice(0, 16);
  const duration = Math.round((Date.now() - input.startedAt) / 3_600_000 * 10) / 10;

  lines.push(`# Session Transcript: ${input.sessionTitle}`);
  lines.push("");
  lines.push(`| Field | Value |`);
  lines.push(`|-------|-------|`);
  lines.push(`| Goal | ${input.goal} |`);
  lines.push(`| Repo | ${input.repo} |`);
  lines.push(`| Status | ${input.status} |`);
  lines.push(`| Started | ${started} |`);
  lines.push(`| Duration | ${duration}h |`);
  lines.push(`| Cost | $${input.costUsd.toFixed(2)} |`);
  lines.push("");

  if (input.progressEntries.length > 0) {
    lines.push("## Progress");
    lines.push("");
    for (const p of input.progressEntries) {
      const time = new Date(p.at).toISOString().slice(11, 19);
      lines.push(`- **${time}** — ${p.summary}`);
    }
    lines.push("");
  }

  if (input.actions.length > 0) {
    lines.push("## Actions");
    lines.push("");
    for (const a of input.actions) {
      const time = new Date(a.at).toISOString().slice(11, 19);
      lines.push(`- **${time}** \`${a.action}\`: ${a.detail}`);
    }
    lines.push("");
  }

  if (input.recentOutput.length > 0) {
    lines.push("## Recent Output");
    lines.push("");
    lines.push("```");
    const stripped = input.recentOutput
      .slice(-50)
      .map((l) => l.replace(/\x1b\[[0-9;]*[mABCDHJKST]/g, ""));
    for (const l of stripped) lines.push(l);
    lines.push("```");
    lines.push("");
  }

  lines.push(`---`);
  lines.push(`*Generated by aoaoe at ${new Date().toISOString().slice(0, 16)}*`);

  return lines.join("\n");
}

/**
 * Build a summary line count for the transcript.
 */
export function transcriptStats(markdown: string): { lines: number; sections: number; chars: number } {
  const allLines = markdown.split("\n");
  const sections = allLines.filter((l) => l.startsWith("## ")).length;
  return { lines: allLines.length, sections, chars: markdown.length };
}

/**
 * Format transcript preview for TUI display.
 */
export function formatTranscriptPreview(input: TranscriptInput): string[] {
  const md = buildTranscript(input);
  const stats = transcriptStats(md);
  const lines: string[] = [];
  lines.push(`  Transcript [${input.sessionTitle}] (${stats.lines} lines, ${stats.sections} sections, ${stats.chars} chars):`);
  const preview = md.split("\n").slice(0, 8);
  for (const l of preview) lines.push(`    ${l}`);
  lines.push(`    ... ${stats.lines - 8} more lines`);
  return lines;
}
